version = 1

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "ember",
    "meteor",
    "angularjs",
    "angular"
  ]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"

[[transformers]]
name = "php-cs-fixer"
enabled = true